In [2]:
string="harini"

In [3]:
string

'harini'

In [6]:
import numpy as np

In [7]:
zero=np.zeros(10)

In [8]:
zero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
one=np.ones(10)

In [11]:
one

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [12]:
array=np.ones(10)*5

In [15]:
array

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [16]:
a=np.arange(10,50)

In [17]:
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [18]:
a=np.arange(10,50,2)

In [19]:
a

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [28]:
array=np.arange(9)

In [29]:
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [31]:
array.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [32]:
array=np.random.rand(1)

In [33]:
array

array([0.07842341])

In [34]:
array=np.random.normal(0,1,25)

In [35]:
array

array([-0.57622382, -0.43385761,  1.78956213, -0.99153037,  0.68292945,
        0.89004513, -0.56239472, -0.05944347,  0.2990883 , -0.76444789,
       -0.06577028,  1.39073325, -1.59555849,  0.02341274, -0.54654251,
        1.64565249, -0.16362739,  0.22044711,  1.73152092, -0.29325204,
        0.18434995, -0.44753068,  1.93520785, -0.6916856 , -1.69795326])

In [39]:
array=np.arange(20).reshape(4,5)

In [40]:
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [41]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [42]:
mat=np.arange(1,26).reshape(5,5)

In [43]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [47]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [48]:
mat[3][4]

20

In [49]:
mat[0:5,1].reshape(5,1)

array([[ 2],
       [ 7],
       [12],
       [17],
       [22]])

In [51]:
mat[4]

array([21, 22, 23, 24, 25])

In [52]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])